/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;
import view.DialogProduk.DataListener;

/**
 *
 * @author rakha
 */
public class PanelTransaksiRetur extends javax.swing.JPanel implements DataListener {

    /**
     * Creates new form PanelTransaksiRetur
     */
    
    private DefaultTableModel model;
    
    public PanelTransaksiRetur() {
        initComponents();
        loadTransaksiRetur("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSupplier = new javax.swing.JLabel();
        formSupplierPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        inputTanggal = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        inputQty = new javax.swing.JTextField();
        cmbRetur = new javax.swing.JComboBox();
        inputProduk = new javax.swing.JTextField();
        btnPilihProduk = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputKeterangan = new javax.swing.JTextArea();
        tabelSupplierPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelRetur = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        textSupplier.setBackground(new java.awt.Color(255, 255, 255));
        textSupplier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textSupplier.setForeground(new java.awt.Color(0, 102, 102));
        textSupplier.setText("Data Transaksi Retur");

        formSupplierPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pilih Produk");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jenis Retur");

        btnSimpan.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 0, 0));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jumlah (Qty)");

        inputQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputQtyKeyTyped(evt);
            }
        });

        cmbRetur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbRetur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ke Supplier", "Dari Pelanggan", " " }));

        inputProduk.setEditable(false);

        btnPilihProduk.setBackground(new java.awt.Color(255, 255, 255));
        btnPilihProduk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPilihProduk.setText("Pilih");
        btnPilihProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihProdukActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Keterangan");

        inputKeterangan.setColumns(20);
        inputKeterangan.setRows(5);
        jScrollPane1.setViewportView(inputKeterangan);

        javax.swing.GroupLayout formSupplierPanelLayout = new javax.swing.GroupLayout(formSupplierPanel);
        formSupplierPanel.setLayout(formSupplierPanelLayout);
        formSupplierPanelLayout.setHorizontalGroup(
            formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSupplierPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formSupplierPanelLayout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addComponent(cmbRetur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputQty)
                    .addComponent(inputTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formSupplierPanelLayout.createSequentialGroup()
                        .addComponent(inputProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPilihProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        formSupplierPanelLayout.setVerticalGroup(
            formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSupplierPanelLayout.createSequentialGroup()
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(inputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSupplierPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)))
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbRetur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelSupplierPanel.setBackground(new java.awt.Color(255, 255, 255));

        tabelRetur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelRetur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelReturMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelRetur);

        javax.swing.GroupLayout tabelSupplierPanelLayout = new javax.swing.GroupLayout(tabelSupplierPanel);
        tabelSupplierPanel.setLayout(tabelSupplierPanelLayout);
        tabelSupplierPanelLayout.setHorizontalGroup(
            tabelSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        tabelSupplierPanelLayout.setVerticalGroup(
            tabelSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-cari.png"))); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tabelSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSupplier)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(inputTanggal.getDate());

            String itemProduk = inputProduk.getText();
            String itemJenisRetur = cmbRetur.getSelectedItem().toString();

            if(itemProduk.contains("--") || itemProduk == "" || itemProduk == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih Produk dan Pelanggan!");
                return;
            }

            String idProduk = itemProduk.split(" - ")[0];

            String qty = inputQty.getText();
            String ket = inputKeterangan.getText();

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "INSERT INTO transaksi_retur (tanggal, id_produk, jenis_retur, qty_retur, keterangan) " +
            "VALUES ('" + tanggal + "', '" + idProduk + "', '" + itemJenisRetur + "', '" + qty + "', '" + ket + "')";
            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Transaksi Berhasil!");
            loadTransaksiRetur("");

            inputTanggal.setDate(null);
            inputProduk.setText("");
            cmbRetur.setSelectedIndex(0);
            inputQty.setText("");
            inputKeterangan.setText("");
            inputTanggal.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Transaksi Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tabelRetur.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dibatalkan dari tabel!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus transaksi ini? Stok produk akan otomatis disesuaikan kembali.",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if(confirm == JOptionPane.YES_OPTION){
            try {
                String idTransaksi = tabelRetur.getValueAt(baris, 0).toString();

                Connection conn = KoneksiDB.getKoneksi();
                Statement stat = conn.createStatement();

                String sql = "DELETE FROM transaksi_retur WHERE id_retur = '" + idTransaksi + "'";
                stat.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Transaksi Berhasil Dibatalkan!");

                loadTransaksiRetur("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelReturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelReturMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelReturMouseClicked

    private void btnPilihProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihProdukActionPerformed
        // TODO add your handling code here:
        DialogProduk dialog = new DialogProduk(new JFrame(), true);
        dialog.setDataListener(this);
        dialog.getContentPane().setBackground(new Color(0, 102, 102));
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPilihProdukActionPerformed

    private void inputQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputQtyKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!Character.isDigit(karakter)) {
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_inputQtyKeyTyped

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword  = inputSearch.getText().trim();
        loadTransaksiRetur(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilihProduk;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbRetur;
    private javax.swing.JPanel formSupplierPanel;
    private javax.swing.JTextArea inputKeterangan;
    private javax.swing.JTextField inputProduk;
    private javax.swing.JTextField inputQty;
    private javax.swing.JTextField inputSearch;
    private com.toedter.calendar.JDateChooser inputTanggal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelRetur;
    private javax.swing.JPanel tabelSupplierPanel;
    private javax.swing.JLabel textSupplier;
    // End of variables declaration//GEN-END:variables

    private void loadTransaksiRetur(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID Retur");
        model.addColumn("Tanggal");
        model.addColumn("Nama Produk");
        model.addColumn("Jenis Retur");
        model.addColumn("Qty Retur");
        model.addColumn("Keterangan");
        tabelRetur.setModel(model);
        StringBuilder sql =  new StringBuilder(
                "SELECT t.id_retur, t.tanggal, b.nama_produk, t.jenis_retur, t.qty_retur, t.keterangan " +
                "FROM transaksi_retur t JOIN master_produk b ON t.id_produk = b.id_produk WHERE 1=1 "
        );

        if (!keyword.isEmpty()) {
            sql.append("AND (t.tanggal LIKE '%" + keyword + "%' OR b.nama_produk LIKE '%" + keyword + "%' OR t.jenis_retur LIKE '%" + keyword + "%') ");
        }

        sql.append("ORDER BY t.tanggal DESC");

        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

//            String sql = "SELECT t.id_retur, t.tanggal, b.nama_produk, t.jenis_retur, t.qty_retur, t.keterangan " +
//                         "FROM transaksi_retur t " +
//                         "JOIN master_produk b ON t.id_produk = b.id_produk " +
//                         "ORDER BY t.tanggal DESC";

            ResultSet rs = stat.executeQuery(sql.toString());

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_retur"),
                    rs.getString("tanggal"),
                    rs.getString("nama_produk"),
                    rs.getString("jenis_retur"),
                    rs.getString("qty_retur"),
                    rs.getString("keterangan")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
    
    public void setProduk(String id, String nama) {
        inputProduk.setText(id+" - "+nama);
        inputProduk.setEnabled(false);
    }

    @Override
    public void onDataSelected(String id, String nama, String stok) {
        inputProduk.setText(id+" - "+nama);
        inputProduk.setEnabled(false);
    }
}
