/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;

/**
 *
 * @author rakha
 */
public class PanelPengguna extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduk
     */
    
    private DefaultTableModel model;
    
    private String hashSHA256(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes("UTF-8"));
            StringBuilder hexString = new StringBuilder();

            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (Exception ex) {
            throw new RuntimeException("Gagal mengenkripsi password", ex);
        }
    }
    
    public PanelPengguna() {
        initComponents();
        loadPengguna();
        kondisiAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPenggunaPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSimpanPengguna = new javax.swing.JButton();
        btnUbahPengguna = new javax.swing.JButton();
        btnHapusPengguna = new javax.swing.JButton();
        inputPassword = new javax.swing.JPasswordField();
        inputRole = new javax.swing.JComboBox();
        btnBatal = new javax.swing.JButton();
        tabelPenggunaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        textPengguna = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        formPenggunaPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Role");

        btnSimpanPengguna.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpanPengguna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpanPengguna.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-simpan.png"))); // NOI18N
        btnSimpanPengguna.setText("Simpan");
        btnSimpanPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPenggunaActionPerformed(evt);
            }
        });

        btnUbahPengguna.setBackground(new java.awt.Color(153, 153, 0));
        btnUbahPengguna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUbahPengguna.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-edit.png"))); // NOI18N
        btnUbahPengguna.setText("Ubah");
        btnUbahPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPenggunaActionPerformed(evt);
            }
        });

        btnHapusPengguna.setBackground(new java.awt.Color(204, 0, 0));
        btnHapusPengguna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapusPengguna.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-hapus.png"))); // NOI18N
        btnHapusPengguna.setText("Hapus");
        btnHapusPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPenggunaActionPerformed(evt);
            }
        });

        inputPassword.setMaximumSize(new java.awt.Dimension(40, 40));
        inputPassword.setPreferredSize(new java.awt.Dimension(425, 40));

        inputRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Gudang" }));
        inputRole.setPreferredSize(new java.awt.Dimension(425, 40));

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPenggunaPanelLayout = new javax.swing.GroupLayout(formPenggunaPanel);
        formPenggunaPanel.setLayout(formPenggunaPanelLayout);
        formPenggunaPanelLayout.setHorizontalGroup(
            formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPenggunaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formPenggunaPanelLayout.createSequentialGroup()
                        .addComponent(btnSimpanPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(inputUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        formPenggunaPanelLayout.setVerticalGroup(
            formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPenggunaPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabelPenggunaPanel.setBackground(new java.awt.Color(255, 255, 255));

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelUser);

        javax.swing.GroupLayout tabelPenggunaPanelLayout = new javax.swing.GroupLayout(tabelPenggunaPanel);
        tabelPenggunaPanel.setLayout(tabelPenggunaPanelLayout);
        tabelPenggunaPanelLayout.setHorizontalGroup(
            tabelPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        tabelPenggunaPanelLayout.setVerticalGroup(
            tabelPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        textPengguna.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textPengguna.setForeground(new java.awt.Color(0, 102, 102));
        textPengguna.setText("Data Pengguna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textPengguna)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formPenggunaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelPenggunaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPengguna)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelPenggunaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formPenggunaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPenggunaActionPerformed
        // TODO add your handling code here:
        try {
            String username = inputUsername.getText();
            // Mengambil password dari JPasswordField
            String password = new String(inputPassword.getPassword()); 
            String role = inputRole.getSelectedItem().toString();

            if (username.isEmpty() || password.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!");
                return;
            }

            String hashedPassword = hashSHA256(password);

            java.sql.Connection conn = koneksi.KoneksiDB.getKoneksi();
            String sql = "INSERT INTO pengguna (username, password, role) VALUES (?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, username);
            pst.setString(2, hashedPassword);
            pst.setString(3, role);

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data Pengguna berhasil ditambahkan!");

            loadPengguna();
            kondisiAwal();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanPenggunaActionPerformed

    private void btnUbahPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPenggunaActionPerformed
        // TODO add your handling code here:
        try {
            int baris = tabelUser.getSelectedRow();
            if (baris == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pengguna dari tabel terlebih dahulu!");
                return;
            }

            String idUser = tabelUser.getValueAt(baris, 0).toString();
            String username = inputUsername.getText();
            String password = new String(inputPassword.getPassword());
            String role = inputRole.getSelectedItem().toString();

            java.sql.Connection conn = koneksi.KoneksiDB.getKoneksi();
            java.sql.PreparedStatement pst;

            if (password.isEmpty()) {
                String sql = "UPDATE pengguna SET username=?, role=? WHERE id_user=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, role);
                pst.setString(3, idUser);
            } else {
                String hashedPassword = hashSHA256(password);
                String sql = "UPDATE pengguna SET username=?, password=?, role=? WHERE id_user=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, hashedPassword);
                pst.setString(3, role);
                pst.setString(4, idUser);
            }

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data Pengguna berhasil diubah!");

            loadPengguna();
            kondisiAwal();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahPenggunaActionPerformed

    private void btnHapusPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPenggunaActionPerformed
        // TODO add your handling code here:
        try {
            int baris = tabelUser.getSelectedRow();
            if (baris == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pengguna dari tabel yang ingin dihapus!");
                return;
            }

            String idUser = tabelUser.getValueAt(baris, 0).toString();
            String username = tabelUser.getValueAt(baris, 1).toString();

            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "Yakin ingin menghapus pengguna: " + username + "?", 
                    "Konfirmasi Hapus", 
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                java.sql.Connection conn = koneksi.KoneksiDB.getKoneksi();
                String sql = "DELETE FROM pengguna WHERE id_user=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, idUser);

                pst.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data Pengguna berhasil dihapus!");

                loadPengguna();
                kondisiAwal();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusPenggunaActionPerformed

    private void tabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUserMouseClicked
        // TODO add your handling code here:
        int baris = tabelUser.rowAtPoint(evt.getPoint());

        if (baris != -1) {
            String nama = tabelUser.getValueAt(baris, 1).toString();
            String role = tabelUser.getValueAt(baris, 2).toString();

            inputUsername.setText(nama);
            switch (role) {
                case "Admin":
                    inputRole.setSelectedIndex(0);
                    break;
                case "Gudang":
                    inputRole.setSelectedIndex(1);
                    break;
            }
        }
        
        btnSimpanPengguna.setEnabled(false);
        btnUbahPengguna.setEnabled(true);
        btnHapusPengguna.setEnabled(true);
    }//GEN-LAST:event_tabelUserMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kondisiAwal();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapusPengguna;
    private javax.swing.JButton btnSimpanPengguna;
    private javax.swing.JButton btnUbahPengguna;
    private javax.swing.JPanel formPenggunaPanel;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JComboBox inputRole;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tabelPenggunaPanel;
    private javax.swing.JTable tabelUser;
    private javax.swing.JLabel textPengguna;
    // End of variables declaration//GEN-END:variables

    private void loadPengguna() {
        model = new DefaultTableModel();
        model.addColumn("ID User");
        model.addColumn("Username");
        model.addColumn("Role");
        tabelUser.setModel(model);

        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery("SELECT id_user, username, role FROM pengguna");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_user"),
                    rs.getString("username"),
                    rs.getString("role")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
    
    private void kondisiAwal() {
        inputUsername.setText("");
        inputPassword.setText("");
        inputRole.setSelectedIndex(0);

        btnSimpanPengguna.setEnabled(true);
        btnUbahPengguna.setEnabled(false);
        btnHapusPengguna.setEnabled(false);

        inputUsername.requestFocus();
    }
}
