/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;

/**
 *
 * @author rakha
 */
public class PanelSupplier extends javax.swing.JPanel {

    /**
     * Creates new form PanelSupplier
     */
    
    private DefaultTableModel model;
    
    public PanelSupplier() {
        initComponents();
        loadSupplier("");
        kondisiAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSupplier = new javax.swing.JLabel();
        formSupplierPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        inputNamaSupplier = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputTelpSupplier = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        inputAlamatSupplier = new javax.swing.JTextField();
        btnSimpanSupplier = new javax.swing.JButton();
        btnUbahSupplier = new javax.swing.JButton();
        btnHapusSupplier = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        tabelSupplierPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelSupplier = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        textSupplier.setBackground(new java.awt.Color(255, 255, 255));
        textSupplier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textSupplier.setForeground(new java.awt.Color(0, 102, 102));
        textSupplier.setText("Data Supplier");

        formSupplierPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No. Telp");

        inputTelpSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTelpSupplierKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alamat");

        btnSimpanSupplier.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpanSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpanSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-simpan.png"))); // NOI18N
        btnSimpanSupplier.setText("Simpan");
        btnSimpanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanSupplierActionPerformed(evt);
            }
        });

        btnUbahSupplier.setBackground(new java.awt.Color(153, 153, 0));
        btnUbahSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUbahSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-edit.png"))); // NOI18N
        btnUbahSupplier.setText("Ubah");
        btnUbahSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahSupplierActionPerformed(evt);
            }
        });

        btnHapusSupplier.setBackground(new java.awt.Color(204, 0, 0));
        btnHapusSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapusSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-hapus.png"))); // NOI18N
        btnHapusSupplier.setText("Hapus");
        btnHapusSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusSupplierActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formSupplierPanelLayout = new javax.swing.GroupLayout(formSupplierPanel);
        formSupplierPanel.setLayout(formSupplierPanelLayout);
        formSupplierPanelLayout.setHorizontalGroup(
            formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSupplierPanelLayout.createSequentialGroup()
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSupplierPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)))
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputTelpSupplier, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputNamaSupplier, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputAlamatSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addComponent(btnSimpanSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formSupplierPanelLayout.setVerticalGroup(
            formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSupplierPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTelpSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAlamatSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabelSupplierPanel.setBackground(new java.awt.Color(255, 255, 255));

        tabelSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSupplierMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelSupplier);

        javax.swing.GroupLayout tabelSupplierPanelLayout = new javax.swing.GroupLayout(tabelSupplierPanel);
        tabelSupplierPanel.setLayout(tabelSupplierPanelLayout);
        tabelSupplierPanelLayout.setHorizontalGroup(
            tabelSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        tabelSupplierPanelLayout.setVerticalGroup(
            tabelSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelSupplierPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-cari.png"))); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSupplier)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanSupplierActionPerformed
        // TODO add your handling code here:
        try {
            String id = generateId();
            String nama = inputNamaSupplier.getText();
            String telp = inputTelpSupplier.getText();
            String alamat = inputAlamatSupplier.getText();

            if(nama.isEmpty() || telp.isEmpty() || alamat.isEmpty()){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "INSERT INTO master_supplier (id_supplier, nama_supplier, no_telp, alamat) "
            + "VALUES ('" + id + "', '" + nama + "', '" + telp + "', '" + alamat + "')";
            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
            loadSupplier("");

            kondisiAwal();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Disimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanSupplierActionPerformed

    private void btnUbahSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahSupplierActionPerformed
        // TODO add your handling code here:
        int baris = tabelSupplier.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin diubah pada tabel terlebih dahulu!");
            return;
        }

        try {
            String id = tabelSupplier.getValueAt(baris, 0).toString();

            String namaBaru = inputNamaSupplier.getText();
            String telpBaru = inputTelpSupplier.getText();
            String alamatBaru = inputAlamatSupplier.getText();

            if(namaBaru.isEmpty() || telpBaru.isEmpty() || alamatBaru.isEmpty()){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "UPDATE master_supplier SET "
            + "nama_supplier = '" + namaBaru + "', "
            + "no_telp = '" + telpBaru + "', "
            + "alamat = '" + alamatBaru + "' "
            + "WHERE id_supplier = '" + id + "'";

            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");

            loadSupplier("");

            kondisiAwal();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahSupplierActionPerformed

    private void btnHapusSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSupplierActionPerformed
        // TODO add your handling code here:
        int baris = tabelSupplier.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus pada tabel!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            try {
                String id = tabelSupplier.getValueAt(baris, 0).toString();
                Connection conn = KoneksiDB.getKoneksi();
                Statement stat = conn.createStatement();

                String sql = "DELETE FROM master_supplier WHERE id_supplier = '" + id + "'";
                stat.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                loadSupplier("");

                kondisiAwal();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusSupplierActionPerformed

    private void tabelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSupplierMouseClicked
        // TODO add your handling code here:
        int baris = tabelSupplier.rowAtPoint(evt.getPoint());

        if (baris != -1) {
            // Kolom 0 -> ID, Kolom 1 -> Nama, Kolom 2 -> Telp, Kolom 3 -> Alamat
            String nama = tabelSupplier.getValueAt(baris, 1).toString();
            String telp = tabelSupplier.getValueAt(baris, 2).toString();
            String alamat = tabelSupplier.getValueAt(baris, 3).toString();

            inputNamaSupplier.setText(nama);
            inputTelpSupplier.setText(telp);
            inputAlamatSupplier.setText(alamat);

            btnSimpanSupplier.setEnabled(false);
            btnUbahSupplier.setEnabled(true);
            btnHapusSupplier.setEnabled(true);
        }
    }//GEN-LAST:event_tabelSupplierMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword  = inputSearch.getText().trim();
        loadSupplier(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputTelpSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTelpSupplierKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!Character.isDigit(karakter)) {
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_inputTelpSupplierKeyTyped

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kondisiAwal();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapusSupplier;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpanSupplier;
    private javax.swing.JButton btnUbahSupplier;
    private javax.swing.JPanel formSupplierPanel;
    private javax.swing.JTextField inputAlamatSupplier;
    private javax.swing.JTextField inputNamaSupplier;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputTelpSupplier;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelSupplier;
    private javax.swing.JPanel tabelSupplierPanel;
    private javax.swing.JLabel textSupplier;
    // End of variables declaration//GEN-END:variables

    private void loadSupplier(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("No. Telp");
        model.addColumn("Alamat");
        tabelSupplier.setModel(model);
        StringBuilder sql =  new StringBuilder(
                "SELECT * " +
                "FROM master_supplier WHERE 1=1 "
        );

        if (!keyword.isEmpty()) {
            sql.append("AND nama_supplier LIKE '%" + keyword + "%' ");
        }

        sql.append("ORDER BY id_supplier ASC");

        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql.toString());

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_supplier"),
                    rs.getString("nama_supplier"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
    
    private String generateId() {
        String idBaru = "SUP-FFD-0001";
        try {
            java.sql.Connection conn = koneksi.KoneksiDB.getKoneksi();
            java.sql.Statement stat = conn.createStatement();

            String sql = "SELECT MAX(RIGHT(id_supplier, 4)) AS no_terakhir FROM master_supplier";
            java.sql.ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                String noTerakhir = rs.getString("no_terakhir");
                if (noTerakhir != null) {
                    int angka = Integer.parseInt(noTerakhir) + 1;
                    idBaru = String.format("SUP-FFD-%04d", angka);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return idBaru;
    }
    
    private void kondisiAwal() {
        inputNamaSupplier.setText("");
        inputTelpSupplier.setText("");
        inputAlamatSupplier.setText("");

        btnSimpanSupplier.setEnabled(true);
        btnUbahSupplier.setEnabled(false);
        btnHapusSupplier.setEnabled(false);

        inputNamaSupplier.requestFocus();
    }
}
