/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;
import view.DialogProduk.DataListener;

/**
 *
 * @author rakha
 */
public class PanelTransaksiKeluar extends javax.swing.JPanel implements DataListener {

    /**
     * Creates new form PanelTransaksiKeluar
     */
    
    private DefaultTableModel model;
    private int stokProduk = 0;
    
    public PanelTransaksiKeluar() {
        initComponents();
        loadTransaksiKeluar("");
//        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSupplier = new javax.swing.JLabel();
        formSupplierPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        inputTanggal = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        inputQty = new javax.swing.JTextField();
        inputProduk = new javax.swing.JTextField();
        inputPelanggan = new javax.swing.JTextField();
        btnPilihProduk = new javax.swing.JButton();
        btnPilihPelanggan = new javax.swing.JButton();
        tabelSupplierPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTransaksiKeluar = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        textSupplier.setBackground(new java.awt.Color(255, 255, 255));
        textSupplier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textSupplier.setForeground(new java.awt.Color(0, 102, 102));
        textSupplier.setText("Data Transaksi Keluar");

        formSupplierPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pilih Produk");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pilih Pelanggan");

        btnSimpan.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 0, 0));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jumlah (Qty)");

        inputQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputQtyKeyTyped(evt);
            }
        });

        inputProduk.setEditable(false);

        inputPelanggan.setEditable(false);

        btnPilihProduk.setBackground(new java.awt.Color(255, 255, 255));
        btnPilihProduk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPilihProduk.setText("Pilih");
        btnPilihProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihProdukActionPerformed(evt);
            }
        });

        btnPilihPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        btnPilihPelanggan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPilihPelanggan.setText("Pilih");
        btnPilihPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formSupplierPanelLayout = new javax.swing.GroupLayout(formSupplierPanel);
        formSupplierPanel.setLayout(formSupplierPanelLayout);
        formSupplierPanelLayout.setHorizontalGroup(
            formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSupplierPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addComponent(inputQty, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addComponent(inputPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPilihPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addComponent(inputProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPilihProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        formSupplierPanelLayout.setVerticalGroup(
            formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSupplierPanelLayout.createSequentialGroup()
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formSupplierPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(inputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSupplierPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)))
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inputPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(formSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabelSupplierPanel.setBackground(new java.awt.Color(255, 255, 255));

        tabelTransaksiKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksiKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiKeluarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelTransaksiKeluar);

        javax.swing.GroupLayout tabelSupplierPanelLayout = new javax.swing.GroupLayout(tabelSupplierPanel);
        tabelSupplierPanel.setLayout(tabelSupplierPanelLayout);
        tabelSupplierPanelLayout.setHorizontalGroup(
            tabelSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        tabelSupplierPanelLayout.setVerticalGroup(
            tabelSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-cari.png"))); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSupplier)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelSupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(inputTanggal.getDate());

            String itemProduk = inputProduk.getText();
            String itemPelanggan = inputPelanggan.getText();

            if(itemProduk.contains("--") || itemPelanggan.contains("--") || itemProduk == "" || itemPelanggan == "" || itemProduk == null || itemPelanggan == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih Produk dan Pelanggan!");
                return;
            }
            

            String idProduk = itemProduk.split(" - ")[0];
            String idPelanggan = itemPelanggan.split(" - ")[0];

            String qty = inputQty.getText();
            
            if (Integer.parseInt(qty) <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Jumlah barang keluar harus lebih dari 0!", 
                    "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                inputQty.requestFocus();
                return;
            }

            if (Integer.parseInt(qty) > stokProduk) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Gagal! Kuantitas melebihi stok. Sisa stok saat ini hanya: " + stokProduk, 
                    "Stok Tidak Cukup", javax.swing.JOptionPane.ERROR_MESSAGE);
                inputQty.setText("");
                inputQty.requestFocus();
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "INSERT INTO transaksi_keluar (tanggal, id_produk, id_pelanggan, qty_keluar) " +
            "VALUES ('" + tanggal + "', '" + idProduk + "', '" + idPelanggan + "', '" + qty + "')";
            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Transaksi Berhasil! Stok barang otomatis berkurang.");
            loadTransaksiKeluar("");

            inputTanggal.setDate(null);
            inputProduk.setText("");
            inputPelanggan.setText("");
            inputQty.setText("");
            inputTanggal.requestFocus();
            inputProduk.setEnabled(false);
            inputPelanggan.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Transaksi Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tabelTransaksiKeluar.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dibatalkan dari tabel!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus transaksi ini? Stok produk akan otomatis disesuaikan kembali.",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if(confirm == JOptionPane.YES_OPTION){
            try {
                String idTransaksi = tabelTransaksiKeluar.getValueAt(baris, 0).toString();

                Connection conn = KoneksiDB.getKoneksi();
                Statement stat = conn.createStatement();

                String sql = "DELETE FROM transaksi_keluar WHERE id_keluar = '" + idTransaksi + "'";
                stat.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Transaksi Berhasil Dibatalkan!");

                loadTransaksiKeluar("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelTransaksiKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelTransaksiKeluarMouseClicked

    private void btnPilihProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihProdukActionPerformed
        // TODO add your handling code here:
        DialogProduk dialog = new DialogProduk(new JFrame(), true);
//        dialog.setPanelTrxKeluar(this);
        dialog.setDataListener(this);
        dialog.getContentPane().setBackground(new Color(0, 102, 102));
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPilihProdukActionPerformed

    private void btnPilihPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihPelangganActionPerformed
        // TODO add your handling code here:
        DialogPelanggan dialog = new DialogPelanggan(new JFrame(), true);
        dialog.setPanelTrxKeluar(this);
        dialog.getContentPane().setBackground(new Color(0, 102, 102));
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPilihPelangganActionPerformed

    private void inputQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputQtyKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!Character.isDigit(karakter)) {
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_inputQtyKeyTyped

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword  = inputSearch.getText().trim();
        loadTransaksiKeluar(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilihPelanggan;
    private javax.swing.JButton btnPilihProduk;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel formSupplierPanel;
    private javax.swing.JTextField inputPelanggan;
    private javax.swing.JTextField inputProduk;
    private javax.swing.JTextField inputQty;
    private javax.swing.JTextField inputSearch;
    private com.toedter.calendar.JDateChooser inputTanggal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel tabelSupplierPanel;
    private javax.swing.JTable tabelTransaksiKeluar;
    private javax.swing.JLabel textSupplier;
    // End of variables declaration//GEN-END:variables

    private void loadTransaksiKeluar(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Nama Produk");
        model.addColumn("Pelanggan");
        model.addColumn("Qty Keluar");
        tabelTransaksiKeluar.setModel(model);
        StringBuilder sql =  new StringBuilder(
                "SELECT t.id_keluar, t.tanggal, b.nama_produk, p.nama_pelanggan, t.qty_keluar " +
                "FROM transaksi_keluar t JOIN master_produk b ON t.id_produk = b.id_produk JOIN master_pelanggan p ON t.id_pelanggan = p.id_pelanggan WHERE 1=1 "
        );

        if (!keyword.isEmpty()) {
            sql.append("AND (t.tanggal LIKE '%" + keyword + "%' OR b.nama_produk LIKE '%" + keyword + "%' OR p.nama_pelanggan LIKE '%" + keyword + "%') ");
        }

        sql.append("ORDER BY t.tanggal DESC");

        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

//            String sql = "SELECT t.id_keluar, t.tanggal, b.nama_produk, p.nama_pelanggan, t.qty_keluar " +
//                         "FROM transaksi_keluar t " +
//                         "JOIN master_produk b ON t.id_produk = b.id_produk " +
//                         "JOIN master_pelanggan p ON t.id_pelanggan = p.id_pelanggan " +
//                         "ORDER BY t.tanggal DESC";

            ResultSet rs = stat.executeQuery(sql.toString());

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_keluar"),
                    rs.getString("tanggal"),
                    rs.getString("nama_produk"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("qty_keluar")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
    
//    private void loadComboBox() {
//        cmbProduk.removeAllItems();
//        cmbPelanggan.removeAllItems();
//
//        cmbProduk.addItem("-- Pilih Produk --");
//        cmbPelanggan.addItem("-- Pilih Pelanggan --");
//
//        try {
//            Connection conn = KoneksiDB.getKoneksi();
//            Statement stat = conn.createStatement();
//
//            ResultSet rsProduk = stat.executeQuery("SELECT id_produk, nama_produk FROM master_produk");
//            while(rsProduk.next()) {
//                cmbProduk.addItem(rsProduk.getString("id_Produk") + " - " + rsProduk.getString("nama_produk"));
//            }
//
//            ResultSet rsSupp = stat.executeQuery("SELECT id_pelanggan, nama_pelanggan FROM master_pelanggan");
//            while(rsSupp.next()) {
//                cmbPelanggan.addItem(rsSupp.getString("id_pelanggan") + " - " + rsSupp.getString("nama_pelanggan"));
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Gagal memuat dropdown: " + e.getMessage());
//        }
//    }
    
    public void setProduk(String id, String nama) {
        inputProduk.setText(id+" - "+nama);
        inputProduk.setEnabled(false);
    }
    
    public void setPelanggan(String id, String nama) {
        inputPelanggan.setText(id+" - "+nama);
        inputPelanggan.setEnabled(false);
    }

    @Override
    public void onDataSelected(String id, String nama, String stok) {
        inputProduk.setText(id+" - "+nama);
        inputProduk.setEnabled(false);
        stokProduk = Integer.parseInt(stok);
    }
}
