/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;

/**
 *
 * @author rakha
 */
public class PanelProduk extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduk
     */
    
    private DefaultTableModel model;
    
    public PanelProduk() {
        initComponents();
        loadProduk("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formProdukPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        inputNamaProduk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputKategoriProduk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputHargaProduk = new javax.swing.JTextField();
        btnSimpanProduk = new javax.swing.JButton();
        btnUbahProduk = new javax.swing.JButton();
        btnHapusProduk = new javax.swing.JButton();
        tabelProdukPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        textProduk = new javax.swing.JLabel();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        formProdukPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Produk");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kategori");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");

        inputHargaProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputHargaProdukKeyTyped(evt);
            }
        });

        btnSimpanProduk.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpanProduk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpanProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanProduk.setText("Simpan");
        btnSimpanProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanProdukActionPerformed(evt);
            }
        });

        btnUbahProduk.setBackground(new java.awt.Color(153, 153, 0));
        btnUbahProduk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUbahProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahProduk.setText("Ubah");
        btnUbahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahProdukActionPerformed(evt);
            }
        });

        btnHapusProduk.setBackground(new java.awt.Color(204, 0, 0));
        btnHapusProduk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapusProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusProduk.setText("Hapus");
        btnHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formProdukPanelLayout = new javax.swing.GroupLayout(formProdukPanel);
        formProdukPanel.setLayout(formProdukPanelLayout);
        formProdukPanelLayout.setHorizontalGroup(
            formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formProdukPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inputKategoriProduk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formProdukPanelLayout.createSequentialGroup()
                        .addComponent(btnSimpanProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputNamaProduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputHargaProduk))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        formProdukPanelLayout.setVerticalGroup(
            formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formProdukPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputKategoriProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputHargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabelProdukPanel.setBackground(new java.awt.Color(255, 255, 255));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProduk);

        javax.swing.GroupLayout tabelProdukPanelLayout = new javax.swing.GroupLayout(tabelProdukPanel);
        tabelProdukPanel.setLayout(tabelProdukPanelLayout);
        tabelProdukPanelLayout.setHorizontalGroup(
            tabelProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        tabelProdukPanelLayout.setVerticalGroup(
            tabelProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        textProduk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textProduk.setForeground(new java.awt.Color(0, 102, 102));
        textProduk.setText("Data Produk");

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textProduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelProdukPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textProduk)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelProdukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanProdukActionPerformed
        // TODO add your handling code here:
        try {
            String id = generateId();
            String nama = inputNamaProduk.getText();
            String kategori = inputKategoriProduk.getText();
            String harga = inputHargaProduk.getText();

            if(nama.isEmpty() || kategori.isEmpty() || harga.isEmpty()){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "INSERT INTO master_produk (id_produk, nama_produk, kategori, harga_satuan, stok) "
            + "VALUES ('" + id + "', '" + nama + "', '" + kategori + "', '" + harga + "', 0)";
            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
            loadProduk("");

            inputNamaProduk.setText("");
            inputKategoriProduk.setText("");
            inputHargaProduk.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Disimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanProdukActionPerformed

    private void btnUbahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahProdukActionPerformed
        // TODO add your handling code here:
        int baris = tabelProduk.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin diubah pada tabel terlebih dahulu!");
            return;
        }

        try {
            String id = tabelProduk.getValueAt(baris, 0).toString();

            String namaBaru = inputNamaProduk.getText();
            String kategoriBaru = inputKategoriProduk.getText();
            String hargaBaru = inputHargaProduk.getText();

            if(namaBaru.isEmpty() || kategoriBaru.isEmpty() || hargaBaru.isEmpty()){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "UPDATE master_produk SET "
            + "nama_produk = '" + namaBaru + "', "
            + "kategori = '" + kategoriBaru + "', "
            + "harga_satuan = '" + hargaBaru + "' "
            + "WHERE id_produk = '" + id + "'";

            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");

            loadProduk("");

            inputNamaProduk.setText("");
            inputKategoriProduk.setText("");
            inputHargaProduk.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahProdukActionPerformed

    private void btnHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProdukActionPerformed
        // TODO add your handling code here:
        int baris = tabelProduk.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus pada tabel!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            try {
                String id = tabelProduk.getValueAt(baris, 0).toString();
                Connection conn = KoneksiDB.getKoneksi();
                Statement stat = conn.createStatement();

                String sql = "DELETE FROM master_produk WHERE id_produk = '" + id + "'";
                stat.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                loadProduk("");

                inputNamaProduk.setText("");
                inputKategoriProduk.setText("");
                inputHargaProduk.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus! Pastikan barang ini tidak memiliki riwayat transaksi.");
            }
        }
    }//GEN-LAST:event_btnHapusProdukActionPerformed

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        // TODO add your handling code here:
        int baris = tabelProduk.rowAtPoint(evt.getPoint());

        if (baris != -1) {
            // Kolom 0 -> ID, Kolom 1 -> Nama, Kolom 2 -> Kategori, Kolom 3 -> Harga
            String nama = tabelProduk.getValueAt(baris, 1).toString();
            String kategori = tabelProduk.getValueAt(baris, 2).toString();
            String harga = tabelProduk.getValueAt(baris, 3).toString();

            inputNamaProduk.setText(nama);
            inputKategoriProduk.setText(kategori);
            inputHargaProduk.setText(ambilAngka(harga));
        }
    }//GEN-LAST:event_tabelProdukMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword  = inputSearch.getText().trim();
        loadProduk(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputHargaProdukKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputHargaProdukKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!Character.isDigit(karakter)) {
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_inputHargaProdukKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusProduk;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpanProduk;
    private javax.swing.JButton btnUbahProduk;
    private javax.swing.JPanel formProdukPanel;
    private javax.swing.JTextField inputHargaProduk;
    private javax.swing.JTextField inputKategoriProduk;
    private javax.swing.JTextField inputNamaProduk;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JPanel tabelProdukPanel;
    private javax.swing.JLabel textProduk;
    // End of variables declaration//GEN-END:variables

    private void loadProduk(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Kategori");
        model.addColumn("Harga Satuan");
        model.addColumn("Stok");
        tabelProduk.setModel(model);
        StringBuilder sql =  new StringBuilder(
                "SELECT * " +
                "FROM master_produk WHERE 1=1 "
        );

        if (!keyword.isEmpty()) {
            sql.append("AND nama_produk LIKE '%" + keyword + "%' ");
        }

        sql.append("ORDER BY id_produk ASC");

        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql.toString());

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_produk"),
                    rs.getString("nama_produk"),
                    rs.getString("kategori"),
                    formatRupiah(rs.getDouble("harga_satuan")),
                    rs.getString("stok")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
    
    private String generateId() {
        String idBaru = "PRD-FFD-0001";
        try {
            java.sql.Connection conn = koneksi.KoneksiDB.getKoneksi();
            java.sql.Statement stat = conn.createStatement();

            String sql = "SELECT MAX(RIGHT(id_produk, 4)) AS no_terakhir FROM master_produk";
            java.sql.ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                String noTerakhir = rs.getString("no_terakhir");
                if (noTerakhir != null) {
                    int angka = Integer.parseInt(noTerakhir) + 1;
                    idBaru = String.format("PRD-FFD-%04d", angka);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return idBaru;
    }
    
    private String formatRupiah(double nominal) {
        return String.format("Rp %,.0f", nominal).replace(",", ".");
    }
    
    private String ambilAngka(String formatRupiah) {
        return formatRupiah.replaceAll("[^\\d]", "");
    }
}
