/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;

/**
 *
 * @author rakha
 */
public class PanelPelanggan extends javax.swing.JPanel {

    /**
     * Creates new form PanelPelanggan
     */
    
    private DefaultTableModel model;
    
    public PanelPelanggan() {
        initComponents();
        loadPelanggan("");
        kondisiAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPelanggan = new javax.swing.JLabel();
        formPelangganPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        inputNamaPelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputTelpPelanggan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputAlamatPelanggan = new javax.swing.JTextField();
        btnSimpanPelanggan = new javax.swing.JButton();
        btnUbahPelanggan = new javax.swing.JButton();
        btnHapusPelanggan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        tabelPelangganPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        textPelanggan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textPelanggan.setForeground(new java.awt.Color(0, 102, 102));
        textPelanggan.setText("Data Pelanggan");

        formPelangganPanel.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. Telp");

        inputTelpPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTelpPelangganKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alamat");

        btnSimpanPelanggan.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpanPelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpanPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-simpan.png"))); // NOI18N
        btnSimpanPelanggan.setText("Simpan");
        btnSimpanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPelangganActionPerformed(evt);
            }
        });

        btnUbahPelanggan.setBackground(new java.awt.Color(153, 153, 0));
        btnUbahPelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUbahPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-edit.png"))); // NOI18N
        btnUbahPelanggan.setText("Ubah");
        btnUbahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPelangganActionPerformed(evt);
            }
        });

        btnHapusPelanggan.setBackground(new java.awt.Color(204, 0, 0));
        btnHapusPelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapusPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-hapus.png"))); // NOI18N
        btnHapusPelanggan.setText("Hapus");
        btnHapusPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPelangganActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPelangganPanelLayout = new javax.swing.GroupLayout(formPelangganPanel);
        formPelangganPanel.setLayout(formPelangganPanelLayout);
        formPelangganPanelLayout.setHorizontalGroup(
            formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPelangganPanelLayout.createSequentialGroup()
                .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPelangganPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPelangganPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)))
                .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputTelpPelanggan)
                    .addComponent(inputNamaPelanggan)
                    .addComponent(inputAlamatPelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPelangganPanelLayout.createSequentialGroup()
                        .addComponent(btnSimpanPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        formPelangganPanelLayout.setVerticalGroup(
            formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPelangganPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTelpPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAlamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(formPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabelPelangganPanel.setBackground(new java.awt.Color(255, 255, 255));

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        javax.swing.GroupLayout tabelPelangganPanelLayout = new javax.swing.GroupLayout(tabelPelangganPanel);
        tabelPelangganPanel.setLayout(tabelPelangganPanelLayout);
        tabelPelangganPanelLayout.setHorizontalGroup(
            tabelPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
        );
        tabelPelangganPanelLayout.setVerticalGroup(
            tabelPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelPelangganPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icon-cari.png"))); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tabelPelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPelanggan)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(412, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPelangganActionPerformed
        // TODO add your handling code here:
        try {
            String id = generateId();
            String nama = inputNamaPelanggan.getText();
            String telp = inputTelpPelanggan.getText();
            String alamat = inputAlamatPelanggan.getText();

            if(nama.isEmpty() || telp.isEmpty() || alamat.isEmpty()){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "INSERT INTO master_pelanggan (id_pelanggan, nama_pelanggan, no_telp, alamat) "
            + "VALUES ('" + id + "', '" + nama + "', '" + telp + "', '" + alamat + "')";
            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
            loadPelanggan("");

            kondisiAwal();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Disimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanPelangganActionPerformed

    private void btnUbahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPelangganActionPerformed
        // TODO add your handling code here:
        int baris = tabelPelanggan.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin diubah pada tabel terlebih dahulu!");
            return;
        }

        try {
            String id = tabelPelanggan.getValueAt(baris, 0).toString();

            String namaBaru = inputNamaPelanggan.getText();
            String telpBaru = inputTelpPelanggan.getText();
            String alamatBaru = inputAlamatPelanggan.getText();

            if(namaBaru.isEmpty() || telpBaru.isEmpty() || alamatBaru.isEmpty()){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();

            String sql = "UPDATE master_pelanggan SET "
            + "nama_pelanggan = '" + namaBaru + "', "
            + "no_telp = '" + telpBaru + "', "
            + "alamat = '" + alamatBaru + "' "
            + "WHERE id_pelanggan = '" + id + "'";

            stat.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");

            loadPelanggan("");

            kondisiAwal();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahPelangganActionPerformed

    private void btnHapusPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPelangganActionPerformed
        // TODO add your handling code here:
        int baris = tabelPelanggan.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus pada tabel!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            try {
                String id = tabelPelanggan.getValueAt(baris, 0).toString();
                Connection conn = KoneksiDB.getKoneksi();
                Statement stat = conn.createStatement();

                String sql = "DELETE FROM master_pelanggan WHERE id_pelanggan = '" + id + "'";
                stat.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                loadPelanggan("");

                kondisiAwal();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusPelangganActionPerformed

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        // TODO add your handling code here:
        int baris = tabelPelanggan.rowAtPoint(evt.getPoint());

        if (baris != -1) {
            // Kolom 0 -> ID, Kolom 1 -> Nama, Kolom 2 -> Telp, Kolom 3 -> Alamat
            String nama = tabelPelanggan.getValueAt(baris, 1).toString();
            String telp = tabelPelanggan.getValueAt(baris, 2).toString();
            String alamat = tabelPelanggan.getValueAt(baris, 3).toString();

            inputNamaPelanggan.setText(nama);
            inputTelpPelanggan.setText(telp);
            inputAlamatPelanggan.setText(alamat);
            
            btnSimpanPelanggan.setEnabled(false);
            btnUbahPelanggan.setEnabled(true);
            btnHapusPelanggan.setEnabled(true);
        }
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword  = inputSearch.getText().trim();
        loadPelanggan(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputTelpPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTelpPelangganKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!Character.isDigit(karakter)) {
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_inputTelpPelangganKeyTyped

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kondisiAwal();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapusPelanggan;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpanPelanggan;
    private javax.swing.JButton btnUbahPelanggan;
    private javax.swing.JPanel formPelangganPanel;
    private javax.swing.JTextField inputAlamatPelanggan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputTelpPelanggan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JPanel tabelPelangganPanel;
    private javax.swing.JLabel textPelanggan;
    // End of variables declaration//GEN-END:variables

    private void loadPelanggan(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("No. Telp");
        model.addColumn("Alamat");
        tabelPelanggan.setModel(model);
        StringBuilder sql =  new StringBuilder(
                "SELECT * " +
                "FROM master_pelanggan WHERE 1=1 "
        );

        if (!keyword.isEmpty()) {
            sql.append("AND nama_pelanggan LIKE '%" + keyword + "%' ");
        }

        sql.append("ORDER BY id_pelanggan ASC");

        try {
            Connection conn = KoneksiDB.getKoneksi();
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql.toString());

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
    
    private String generateId() {
        String idBaru = "PLG-FFD-0001";
        try {
            java.sql.Connection conn = koneksi.KoneksiDB.getKoneksi();
            java.sql.Statement stat = conn.createStatement();

            String sql = "SELECT MAX(RIGHT(id_pelanggan, 4)) AS no_terakhir FROM master_pelanggan";
            java.sql.ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                String noTerakhir = rs.getString("no_terakhir");
                if (noTerakhir != null) {
                    int angka = Integer.parseInt(noTerakhir) + 1;
                    idBaru = String.format("PLG-FFD-%04d", angka);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return idBaru;
    }
    
    private void kondisiAwal() {
        inputNamaPelanggan.setText("");
        inputTelpPelanggan.setText("");
        inputAlamatPelanggan.setText("");

        btnSimpanPelanggan.setEnabled(true);
        btnUbahPelanggan.setEnabled(false);
        btnHapusPelanggan.setEnabled(false);

        inputNamaPelanggan.requestFocus();
    }
}
