/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author rakha
 */
public class DashboardUtama extends javax.swing.JFrame {

    /**
     * Creates new form DashboardUtama
     */
    public DashboardUtama() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMenuUtama = new javax.swing.JButton();
        btnDataMaster = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        panelUtama = new javax.swing.JPanel();
        viewMenuUtama = new javax.swing.JPanel();
        textMenuUtama = new javax.swing.JLabel();
        viewDataMaster = new javax.swing.JPanel();
        textDataMaster = new javax.swing.JLabel();
        viewTransaksi = new javax.swing.JPanel();
        textTransaksi = new javax.swing.JLabel();
        viewLaporan = new javax.swing.JPanel();
        textLaporan = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 768));

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));
        headerPanel.setPreferredSize(new java.awt.Dimension(0, 60));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FiveFrost Delights");
        headerPanel.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setPreferredSize(new java.awt.Dimension(85, 25));
        headerPanel.add(jButton1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Role");

        btnMenuUtama.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuUtama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMenuUtama.setForeground(new java.awt.Color(0, 102, 102));
        btnMenuUtama.setText("Menu Utama");
        btnMenuUtama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenuUtama.setPreferredSize(new java.awt.Dimension(200, 50));
        btnMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtamaActionPerformed(evt);
            }
        });

        btnDataMaster.setBackground(new java.awt.Color(255, 255, 255));
        btnDataMaster.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDataMaster.setForeground(new java.awt.Color(0, 102, 102));
        btnDataMaster.setText("Data Master");
        btnDataMaster.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDataMaster.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDataMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataMasterActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(0, 102, 102));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaksi.setPreferredSize(new java.awt.Dimension(200, 50));
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(0, 102, 102));
        btnLaporan.setText("Laporan");
        btnLaporan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLaporan.setPreferredSize(new java.awt.Dimension(200, 50));
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3))
                            .addComponent(btnMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDataMaster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(btnMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnDataMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        panelUtama.setLayout(new java.awt.CardLayout());

        textMenuUtama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textMenuUtama.setForeground(new java.awt.Color(0, 102, 102));
        textMenuUtama.setText("Menu Utama");

        javax.swing.GroupLayout viewMenuUtamaLayout = new javax.swing.GroupLayout(viewMenuUtama);
        viewMenuUtama.setLayout(viewMenuUtamaLayout);
        viewMenuUtamaLayout.setHorizontalGroup(
            viewMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textMenuUtama)
                .addContainerGap(677, Short.MAX_VALUE))
        );
        viewMenuUtamaLayout.setVerticalGroup(
            viewMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textMenuUtama)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        panelUtama.add(viewMenuUtama, "card2");

        textDataMaster.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textDataMaster.setForeground(new java.awt.Color(0, 102, 102));
        textDataMaster.setText("Data Master");

        javax.swing.GroupLayout viewDataMasterLayout = new javax.swing.GroupLayout(viewDataMaster);
        viewDataMaster.setLayout(viewDataMasterLayout);
        viewDataMasterLayout.setHorizontalGroup(
            viewDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDataMasterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDataMaster)
                .addContainerGap(682, Short.MAX_VALUE))
        );
        viewDataMasterLayout.setVerticalGroup(
            viewDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDataMasterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDataMaster)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        panelUtama.add(viewDataMaster, "card3");

        textTransaksi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textTransaksi.setForeground(new java.awt.Color(0, 102, 102));
        textTransaksi.setText("Transaksi");

        javax.swing.GroupLayout viewTransaksiLayout = new javax.swing.GroupLayout(viewTransaksi);
        viewTransaksi.setLayout(viewTransaksiLayout);
        viewTransaksiLayout.setHorizontalGroup(
            viewTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTransaksi)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        viewTransaksiLayout.setVerticalGroup(
            viewTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTransaksi)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        panelUtama.add(viewTransaksi, "card4");

        textLaporan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textLaporan.setForeground(new java.awt.Color(0, 102, 102));
        textLaporan.setText("Laporan");

        javax.swing.GroupLayout viewLaporanLayout = new javax.swing.GroupLayout(viewLaporan);
        viewLaporan.setLayout(viewLaporanLayout);
        viewLaporanLayout.setHorizontalGroup(
            viewLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLaporan)
                .addContainerGap(727, Short.MAX_VALUE))
        );
        viewLaporanLayout.setVerticalGroup(
            viewLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLaporan)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        panelUtama.add(viewLaporan, "card5");

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtamaActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.add(viewMenuUtama);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_btnMenuUtamaActionPerformed

    private void btnDataMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMasterActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.add(viewDataMaster);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_btnDataMasterActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.add(viewTransaksi);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.add(viewLaporan);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataMaster;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMenuUtama;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel textDataMaster;
    private javax.swing.JLabel textLaporan;
    private javax.swing.JLabel textMenuUtama;
    private javax.swing.JLabel textTransaksi;
    private javax.swing.JPanel viewDataMaster;
    private javax.swing.JPanel viewLaporan;
    private javax.swing.JPanel viewMenuUtama;
    private javax.swing.JPanel viewTransaksi;
    // End of variables declaration//GEN-END:variables
}
